### ISSUE TITLE
How is performance and latency affected by RU reserve capacity?

### ISSUE THREAD

**Issue by jaybo** [delange/cosmosdb-spatial-query-perf#3]
In the setup for the experiment you mentioned provisioning 10,000 RU's.  Which costs roughly $584/month.  Gak!

If running the same experiment with (say) one query per second and the default 400 RU capacity, is the performance in terms of latency and RUs consumed identical to the results given?

Thanks!

**Comment by delange** [comment]
Yes, it should be the same. 
RU cost will be the same, performance will depends on the number of query per second but with 1 per sec it should be the same.
